"""
CNN Beacon Classifier Training Script
======================================
Trains a small CNN on the synthetic dataset generated by
generate_training_data.py.

Architecture: BeaconCNN
  Input:  (1, 32, 32) grayscale patch, normalized [0,1]
  Conv1:  8 filters, 3x3, ReLU, BatchNorm
  Pool1:  2x2 MaxPool → (8, 16, 16)
  Conv2:  16 filters, 3x3, ReLU, BatchNorm
  Pool2:  2x2 MaxPool → (16, 8, 8)
  Conv3:  32 filters, 3x3, ReLU, BatchNorm
  Pool3:  2x2 MaxPool → (32, 4, 4)
  Flatten → 512
  FC1:    512 → 64, ReLU, Dropout(0.4)
  FC2:    64 → 2
  Output: softmax probabilities [P(distractor), P(beacon)]

Designed for CPU inference in < 2ms per patch.
Total parameters: ~25,000 (tiny by design — fast and explainable)

Saves trained model to: models/beacon_classifier.pt
"""

import os
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import time

DATA_DIR  = os.path.join('data', 'training')
MODEL_DIR = 'models'
MODEL_PATH = os.path.join(MODEL_DIR, 'beacon_classifier.pt')
os.makedirs(MODEL_DIR, exist_ok=True)

# Training config
BATCH_SIZE   = 64
EPOCHS       = 25
LR           = 1e-3
LR_STEP      = 10       # reduce LR every N epochs
LR_GAMMA     = 0.5
WEIGHT_DECAY = 1e-4

torch.manual_seed(42)
np.random.seed(42)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Training on: {DEVICE}")


# ── Dataset ──────────────────────────────────────────────────────────────────

class PatchDataset(Dataset):
    def __init__(self, patches_path, labels_path, augment=False):
        self.patches = np.load(patches_path)   # (N, 32, 32) float32
        self.labels  = np.load(labels_path)    # (N,) int64
        self.augment = augment

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        patch = self.patches[idx].copy()   # (32, 32) float32

        if self.augment:
            # Random horizontal flip
            if np.random.random() < 0.5:
                patch = np.fliplr(patch).copy()
            # Random vertical flip
            if np.random.random() < 0.5:
                patch = np.flipud(patch).copy()
            # Random 90-degree rotation
            k = np.random.randint(0, 4)
            patch = np.rot90(patch, k).copy()
            # Brightness jitter
            jitter = np.random.uniform(0.85, 1.15)
            patch = np.clip(patch * jitter, 0, 1)
            # Small Gaussian noise
            patch = np.clip(
                patch + np.random.normal(0, 0.02, patch.shape), 0, 1
            ).astype(np.float32)

        # Add channel dim: (32,32) → (1,32,32)
        tensor = torch.from_numpy(patch).unsqueeze(0)
        label  = torch.tensor(int(self.labels[idx]), dtype=torch.long)
        return tensor, label


# ── Model ────────────────────────────────────────────────────────────────────

class BeaconCNN(nn.Module):
    """
    Small CNN for beacon vs. distractor classification.
    Designed for fast CPU inference (< 2ms per patch).
    ~25,000 parameters.
    """
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            # Block 1: (1,32,32) → (8,16,16)
            nn.Conv2d(1, 8, kernel_size=3, padding=1),
            nn.BatchNorm2d(8),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),               # → (8,16,16)

            # Block 2: (8,16,16) → (16,8,8)
            nn.Conv2d(8, 16, kernel_size=3, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),               # → (16,8,8)

            # Block 3: (16,8,8) → (32,4,4)
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),               # → (32,4,4)
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),                  # → 512
            nn.Linear(32 * 4 * 4, 64),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(64, 2),              # → [P(distractor), P(beacon)]
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

    def predict_proba(self, patch_tensor):
        """
        Single patch inference. Returns P(beacon) as float.
        patch_tensor: (1, 32, 32) float32 tensor
        """
        with torch.no_grad():
            out = self.forward(patch_tensor.unsqueeze(0))
            prob = torch.softmax(out, dim=1)
            return float(prob[0, 1])   # P(beacon)


# ── Training ─────────────────────────────────────────────────────────────────

# v1 file names; --v2 switches to data/training_v2 (see
# detection/generate_training_data.py --v2) and models/beacon_classifier_v2.pt.
TRAIN_PREFIX = 'beacon'


def train():
    # Load datasets
    print("Loading datasets...")
    train_ds = PatchDataset(
        os.path.join(DATA_DIR, f'{TRAIN_PREFIX}_patches.npy'),
        os.path.join(DATA_DIR, f'{TRAIN_PREFIX}_labels.npy'),
        augment=True
    )
    val_ds = PatchDataset(
        os.path.join(DATA_DIR, 'val_patches.npy'),
        os.path.join(DATA_DIR, 'val_labels.npy'),
        augment=False
    )
    test_ds = PatchDataset(
        os.path.join(DATA_DIR, 'test_patches.npy'),
        os.path.join(DATA_DIR, 'test_labels.npy'),
        augment=False
    )

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE,
                              shuffle=True, num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE,
                              shuffle=False, num_workers=0)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE,
                              shuffle=False, num_workers=0)

    print(f"Train: {len(train_ds)} | Val: {len(val_ds)} | Test: {len(test_ds)}")

    model = BeaconCNN().to(DEVICE)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {total_params:,}")

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LR,
                           weight_decay=WEIGHT_DECAY)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=LR_STEP,
                                           gamma=LR_GAMMA)

    best_val_acc = 0.0
    best_epoch   = 0

    print(f"\nTraining for {EPOCHS} epochs...")
    print("-" * 55)

    for epoch in range(1, EPOCHS + 1):
        t0 = time.time()

        # ── Train ──
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for patches, labels in train_loader:
            patches = patches.to(DEVICE)
            labels  = labels.to(DEVICE)

            optimizer.zero_grad()
            outputs = model(patches)
            loss    = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss    += loss.item() * len(labels)
            preds          = outputs.argmax(dim=1)
            train_correct += (preds == labels).sum().item()
            train_total   += len(labels)

        train_acc  = train_correct / train_total
        train_loss = train_loss / train_total

        # ── Validate ──
        model.eval()
        val_correct = 0
        val_total   = 0

        with torch.no_grad():
            for patches, labels in val_loader:
                patches = patches.to(DEVICE)
                labels  = labels.to(DEVICE)
                outputs = model(patches)
                preds   = outputs.argmax(dim=1)
                val_correct += (preds == labels).sum().item()
                val_total   += len(labels)

        val_acc = val_correct / val_total
        elapsed = time.time() - t0

        print(f"Epoch {epoch:02d}/{EPOCHS} | "
              f"Loss: {train_loss:.4f} | "
              f"Train: {train_acc*100:.1f}% | "
              f"Val: {val_acc*100:.1f}% | "
              f"LR: {scheduler.get_last_lr()[0]:.2e} | "
              f"{elapsed:.1f}s")

        # Save best model
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_epoch   = epoch
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'val_acc': val_acc,
                'train_acc': train_acc,
            }, MODEL_PATH)

        scheduler.step()

    print("-" * 55)
    print(f"Best val accuracy: {best_val_acc*100:.1f}% (epoch {best_epoch})")

    # ── Test on held-out set ──
    print("\nEvaluating on test set...")
    checkpoint = torch.load(MODEL_PATH, map_location=DEVICE)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()

    test_correct = 0
    test_total   = 0
    tp = tn = fp = fn = 0

    with torch.no_grad():
        for patches, labels in test_loader:
            patches = patches.to(DEVICE)
            labels  = labels.to(DEVICE)
            outputs = model(patches)
            preds   = outputs.argmax(dim=1)
            test_correct += (preds == labels).sum().item()
            test_total   += len(labels)

            # Confusion matrix elements
            tp += ((preds == 1) & (labels == 1)).sum().item()
            tn += ((preds == 0) & (labels == 0)).sum().item()
            fp += ((preds == 1) & (labels == 0)).sum().item()
            fn += ((preds == 0) & (labels == 1)).sum().item()

    test_acc   = test_correct / test_total
    precision  = tp / (tp + fp + 1e-9)
    recall     = tp / (tp + fn + 1e-9)
    f1         = 2 * precision * recall / (precision + recall + 1e-9)

    print(f"Test Accuracy:  {test_acc*100:.1f}%")
    print(f"Precision:      {precision*100:.1f}%  (of predicted beacons, % correct)")
    print(f"Recall:         {recall*100:.1f}%  (of real beacons, % found)")
    print(f"F1 Score:       {f1*100:.1f}%")
    print(f"Confusion:      TP={tp} TN={tn} FP={fp} FN={fn}")

    # Per-condition held-out accuracy (v2 data carries a condition label).
    cond_path = os.path.join(DATA_DIR, 'test_cond.npy')
    if os.path.exists(cond_path):
        from detection.generate_training_data import V2_GROUP
        cond = np.load(cond_path)
        with torch.no_grad():
            x = torch.from_numpy(test_ds.patches).unsqueeze(1).to(DEVICE)
            preds = model(x).argmax(dim=1).cpu().numpy()
        ok = preds == test_ds.labels
        groups = np.array([V2_GROUP.get(c, c) for c in cond])
        print("Per-condition test accuracy:")
        for g in ('clean', 'noise', 'fog', 'distractor'):
            m = groups == g
            if m.any():
                b = m & (test_ds.labels == 1)
                print(f"  {g:10s} {ok[m].mean()*100:5.1f}%  (n={m.sum()}, "
                      f"beacon recall {ok[b].mean()*100 if b.any() else float('nan'):.1f}%)")

    # ── Inference speed benchmark ──
    print("\nBenchmarking inference speed...")
    model.eval()
    dummy = torch.randn(1, 1, 32, 32).to(DEVICE)
    # Warmup
    for _ in range(10):
        with torch.no_grad():
            model(dummy)
    # Benchmark
    t0 = time.perf_counter()
    N_BENCH = 500
    for _ in range(N_BENCH):
        with torch.no_grad():
            model(dummy)
    elapsed_ms = (time.perf_counter() - t0) * 1000 / N_BENCH
    print(f"Inference time: {elapsed_ms:.3f} ms per patch (CPU)")
    print(f"Max candidates before 3ms budget: "
          f"{int(3.0 / elapsed_ms)} candidates")

    print(f"\nModel saved to: {MODEL_PATH}")


if __name__ == '__main__':
    import sys
    if '--v2' in sys.argv:
        DATA_DIR = os.path.join('data', 'training_v2')
        MODEL_PATH = os.path.join(MODEL_DIR, 'beacon_classifier_v2.pt')
        TRAIN_PREFIX = 'train'
    train()
